version: '3'
services:
  jenkins:
    image: quiram/jenkins-kubernetes
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_kubernetes_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ci_network
    environment:
      - docker_network_name=jenkinskubernetes_ci_network

volumes:
  jenkins_kubernetes_home:

networks:
  ci_network:
    driver: bridge
